# Generated by Django 4.1.6 on 2023-03-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('name_with_initials', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('nic', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=1)),
                ('job', models.CharField(max_length=50)),
                ('Relation', models.CharField(max_length=2)),
                ('special_notes', models.JSONField()),
            ],
        ),
    ]
